;   PlatformIO Project Configuration File
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; Arduino Core https://github.com/sivar2311/platform-espressif32-versions
; Manual       https://alexgyver.ru/lessons/platformio/

[platformio]
default_envs = esp32-wroom, esp32-wrover-kit, esp32-wrover-n16r8, esp32-s3-n4r2, esp32-s3-n8r8, esp32-s3-n16r8

; --- СПІЛЬНІ НАЛАШТУВАННЯ ДЛЯ YORADIO ---
[env_common]
; Arduino 2.0.17
;platform = espressif32 @ 6.12.0  ; Arduino 2.0.17 Arduino Core 4.4.7
platform = espressif32  ;  Arduino 2.0.17 качає саму свіжу

framework = arduino
board_build.f_cpu = 240000000L  ; Налаштування частоти процесора
; --- Параметри завантаження ---
board_build.filesystem = spiffs
upload_protocol = esptool
upload_speed = 921600
; Додаткові налаштування для коректної збірки PSRAM на Windows/Linux
build_type = release

; --- Прапори компіляції ---
build_unflags = -std=gnu++11  ; Видалення параметрів C++11 за замовчуванням.

common_build_flags =
    -std=gnu++2a  ; Встановлює налаштування C++20 за промовчанням.
	-fno-exceptions
	-Wall
    -Wextra
    -O2
	; --- Розподіл ядер (Core 0 - Audio/WiFi, Core 1 - UI/Main)
	-D ARDUINO_RUNNING_CORE=1                ; Arduino Runs On Core (setup, loop)
	-D ARDUINO_EVENT_RUNNING_CORE=1          ; Events Run On Core
	-D WIFI_TASK_PRIORITY=5        ; Стандартний пріоритет WiFi
	-D AUDIOTASK_CORE=0                      ; 0 or 1 - reads from the InBuffer, decodes and feeds I2S
	-D AUDIOCONTROLTASK_PRIO=4     ; Робимо аудіо трохи нижче за WiFi, але вище за все інше
	-D UI_TASK_PRIO=2        	   ; Вище за loop (1), але нижче за аудіо
	; Діагностика та кольоровий лог ---
    -D CORE_DEBUG_LEVEL=2
    -D CONFIG_ARDUHAL_LOG_COLORS=1
	-fdiagnostics-color=always

extra_scripts = pre:copy_glcdfont.py

; --- Монітор ---
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize
monitor_dtr = 0
monitor_rts = 0

; --- Бібліотеки ---
lib_deps =
	adafruit/Adafruit BusIO
;	adafruit/Adafruit GFX Library
;	adafruit/Adafruit ILI9341
;	adafruit/Adafruit SH110X
;	adafruit/Adafruit SSD1305
;	adafruit/Adafruit SSD1306
;	aki237/Adafruit_ESP32_SH1106
;	adafruit/Adafruit SSD1327
;	adafruit/Adafruit ST7735 and ST7789 Library
;	adafruit/Adafruit NeoPixel
;	adafruit/RTClib
;	bblanchon/ArduinoJson
;	crankyoldgit/IRremoteESP8266
;	mathertel/OneButton
;	PaulStoffregen/XPT2046_Touchscreen

; --- КОНФІГУРАЦІЯ ДЛЯ ESP32 WROOM ---
[env:esp32-wroom]
extends = env_common
board = esp32dev
board_build.flash_mode = qio   ; dio
;40000000L (40 МГц): Найбільш стабільний та сумісний варіант. За замовчуванням використовується багато плат, якщо 80 МГц працює нестабільно.
;80000000L (80 МГц): Стандартна максимальна частота для більшості модулів ESP32. Забезпечує кращу продуктивність під час читання коду з flash.
board_build.f_flash = 80000000L
board_upload.flash_size = 4MB
; --- Параметри завантаження ---
board_build.partitions = partitions_4MB.csv
board_upload.maximum_size = 1966080  ; 1,875mb
build_unflags = ${env_common.build_unflags}
build_flags = ${env_common.common_build_flags}

; --- КОНФІГУРАЦІЯ ДЛЯ ESP32 WROVER (4MB) ---
[env:esp32-wrover-kit]
extends = env_common
board = esp-wrover-kit
; КРИТИЧНІ налаштування (Flash + PSRAM)
;40000000L (40 МГц): Найбільш стабільний та сумісний варіант. За замовчуванням використовується багато плат, якщо 80 МГц працює нестабільно.
;80000000L (80 МГц): Стандартна максимальна частота для більшості модулів ESP32. Забезпечує кращу продуктивність під час читання коду з flash.
board_build.f_flash = 80000000L
board_build.f_psram = 40000000L
board_build.flash_mode = qio
board_upload.flash_size = 4MB

; --- Параметри завантаження ---
board_build.partitions = partitions_4MB.csv
board_upload.maximum_size = 1966080  ; 1,875mb

build_unflags = ${env_common.build_unflags}

build_flags =
	${env_common.common_build_flags}
; --- Активація PSRAM ---
    -D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue ; КРИТИЧНО для стабільних WROVER з PSRAM
; --- Графіка
; 20000000L (20 МГц): Більш стабільний режим. Варто використовувати, якщо дисплей підключений довгими дротами або ви бачите "сміття" на екрані.
; 40000000L (40 МГц): Стандарт для більшості дисплеїв (ILI9341, ST7789). Забезпечує дуже швидке оновлення інтерфейсу радіо.
; 80000000L (80 МГц): Теоретичний максимум. Деякі сучасні дисплеї працюють, але на такій частоті навіть коротка довжина дротів або відсутність екранування може призвести до збоїв.
    -D DEF_SPI_FREQ=80000000UL

; --- КОНФІГУРАЦІЯ ДЛЯ ESP32 WROVER (N16R8) ---
[env:esp32-wrover-n16r8]
extends = env_common
board = esp32-wrover-n16r8
; КРИТИЧНІ налаштування (Flash + PSRAM)
;40000000L (40 МГц): Найбільш стабільний та сумісний варіант. За замовчуванням використовується багато плат, якщо 80 МГц працює нестабільно.
;80000000L (80 МГц): Стандартна максимальна частота для більшості модулів ESP32. Забезпечує кращу продуктивність під час читання коду з flash.
board_build.f_flash = 80000000L
board_build.f_psram = 40000000L
board_build.psram_type = qio
board_build.flash_mode = qio
board_upload.flash_size = 16MB
; --- Параметри завантаження ---
board_build.partitions = partitions_16MB.csv  ; 3mb + 3mb + 9,8mb
board_upload.maximum_size = 3145728  ; 3mb

build_unflags = ${env_common.build_unflags}
build_flags =
	${env_common.common_build_flags}
; --- Активація PSRAM ---
    -D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue ; КРИТИЧНО для стабільних WROVER з PSRAM
; --- Графіка
; 20000000L (20 МГц): Більш стабільний режим. Варто використовувати, якщо дисплей підключений довгими дротами або ви бачите "сміття" на екрані.
; 40000000L (40 МГц): Стандарт для більшості дисплеїв (ILI9341, ST7789). Забезпечує дуже швидке оновлення інтерфейсу радіо.
; 80000000L (80 МГц): Теоретичний максимум. Деякі сучасні дисплеї працюють, але на такій частоті навіть коротка довжина дротів або відсутність екранування може призвести до збоїв.
    -D DEF_SPI_FREQ=80000000UL

; --- КОНФІГУРАЦІЯ ДЛЯ ESP32-S3 (N4R2) ---
[env:esp32-s3-n4r2]
extends = env_common
board = esp32-s3-n4r2
board_build.f_flash = 80000000L   ; Налаштування частоти Flash
board_build.f_psram = 80000000L
board_build.arduino.memory_type = qio_qio   ; Quad для Flash и PSRAM
board_build.psram_type = qio
board_build.flash_mode = qio
board_upload.flash_size = 4MB
; --- Параметри завантаження ---
board_build.partitions = partitions_4MB.csv
board_upload.maximum_size = 1966080  ; 1,875mb

build_unflags = ${env_common.build_unflags}
build_flags =
	${env_common.common_build_flags}
; --- Активація PSRAM ---
    -D BOARD_HAS_PSRAM
; --- Графіка
    -D DEF_SPI_FREQ=80000000UL
; --- Налаштування USB (S3 має вбудований USB-Serial)
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; --- КОНФІГУРАЦІЯ ДЛЯ ESP32-S3 (N8R8) ---
[env:esp32-s3-n8r8]
extends = env_common
board = esp32-s3-n8r8
board_build.f_flash = 80000000L   ; Налаштування частоти Flash
board_build.f_psram = 80000000L
board_build.arduino.memory_type = qio_opi   ; Quad для Flash и PSRAM
board_build.psram_type = opi
board_build.flash_mode = qio
board_upload.flash_size = 8MB
; --- Параметри завантаження ---
board_build.partitions = partitions_8MB.csv  ; 3mb + 3mb + 1,8mb
board_upload.maximum_size = 3145728  ; 3mb

build_unflags = ${env_common.build_unflags}
build_flags =
	${env_common.common_build_flags}
; --- Активація PSRAM ---
    -D BOARD_HAS_PSRAM
; --- Графіка
    -D DEF_SPI_FREQ=80000000UL
; --- Налаштування USB (S3 має вбудований USB-Serial)
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
	
[env:esp32-s3-n16r8]
extends = env_common
board = esp32-s3-n16r8
;40000000L (40 МГц): Найбільш стабільний та сумісний варіант. За замовчуванням використовується багато плат, якщо 80 МГц працює нестабільно.
;80000000L (80 МГц): Стандартна максимальна частота для більшості модулів ESP32. Забезпечує кращу продуктивність під час читання коду з flash.
;120000000L (120 МГц): Підтримується тільки в ESP32-S3 (і деяких нових моделях) у режимі High Performance (DDR).
board_build.f_flash = 80000000L   ; Налаштування частоти Flash
board_build.f_psram = 80000000L
;qio_no_psram: Використовується Quad I/O для Flash, зовнішня оперативна пам'ять відсутня.
;dio_no_psram: Використовується Dual I/O для Flash (більш сумісний режим), без PSRAM.
;qio_qspi: Flash працює через Quad SPI, і PSRAM також через Quad SPI. Це стандарт для більшості модулів ESP32-S3-WROOM-1.
;opi_opi: Найшвидший режим (Octal SPI). І Flash, і PSRAM використовують 8 ліній даних. Це характерно для модулів з великим об'ємом пам'яті (наприклад, 16MB Flash / 8MB PSRAM).
;qio_opi: Flash працює через 4 лінії (Quad), а PSRAM — через 8 ліній (Octal).
;opi_qspi: Flash — Octal, PSRAM — Quad.
board_build.arduino.memory_type = qio_opi   ; Quad для Flash и PSRAM
;qout (Quad Output): Використовує 4 лінії для читання даних, але адресу надсилає по одній лінії. Трохи повільніший за qio, але стабільніший на деяких чипах.
;dio (Dual I/O): Використовує 2 лінії для адреси та читання. Це звільняє контакти GPIO9 та GPIO10 для вашого використання (якщо вони не заведені всередині модуля).
;dout (Dual Output): Найповільніший, але найсумісніший режим. Використовує 2 лінії тільки для виведення даних. Саме цей режим часто є єдиним робочим для модулів ESP8285.
;opi (Octal SPI): Новий режим для сучасних чипів (наприклад, ESP32-S3), який використовує 8 ліній для передачі даних, що забезпечує максимальну швидкість.
board_build.flash_mode = qio
;qspi (Quad SPI) — використовується для стандартних модулів PSRAM, які працюють через 4 лінії даних. Це найтиповіший варіант для базових модулів ESP32 та ESP32-S3 (наприклад, у моделях з 2MB або 4MB PSRAM).
;opi (Octal SPI) — використовується для високошвидкісної пам'яті, що працює через 8 ліній даних. Це характерно для "просунутих" модулів ESP32-S3 (наприклад, у конфігураціях R8 — 8MB PSRAM).
board_build.psram_type = opi
board_upload.flash_size = 16MB
; --- Параметри завантаження ---
board_build.partitions = partitions_16MB.csv  ; 3mb + 3mb + 9,8mb
board_upload.maximum_size = 3145728  ; 3mb

build_unflags = ${env_common.build_unflags}
build_flags =
	${env_common.common_build_flags}
; --- Активація PSRAM ---
    -D BOARD_HAS_PSRAM
; --- Графіка
    -D DEF_SPI_FREQ=80000000UL
; --- Налаштування USB (S3 має вбудований USB-Serial)
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
